name: Update Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: vitormouragit
          options: bg_color=0B1F3A&color=FFFFFF&line=1E90FF&point=FFFFFF&area=true&hide_border=true
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show generated files
        run: |
          echo "Arquivos gerados:"
          find dist -type f -print

      - name: Publish to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin output || true

          if git show-ref --verify --quiet refs/remotes/origin/output; then
            git checkout output
          else
            git checkout --orphan output
            git rm -rf . || true
          fi

          cp dist/activity-graph.svg ./activity-graph.svg

          git add activity-graph.svg
          git commit -m "Update activity graph" || echo "No changes"
          git push origin output
